nama = input("Masukan nama lengkap: ")
ttl = input("Masukan tempat tanggal lahir: ")
alamat = input("masukan alamat: ")
hp = input("Masukan no hp: ")
study = input("Masukan program study: ")
hobby = input("Masukan hobi: ") 
print("\n")
print("Nama lengkap: ", nama)
print("Tempat tanggal lahir: ", ttl)
print("Alamat: ", alamat)
print("no.hp: ", hp)
print("Program Study: ", study)
print("Hobi: ", hobby)